### ISSUE TITLE
Inquiry on parameters for the filters and how to use this package

### ISSUE THREAD

**Issue by PhilipAmadasun** [ros-perception/laser_filters#151]
I am trying to use the laser_filters package to filter out fake obstacles that my lidar keeps detecting. I set my paramters in my yaml file and roslaunch the filter from a launch file. I have no idea if I'm doing something wrong because it seems to run but doesn't seem to work. I need help figuring out how to use this package. Here is my yaml file:
 ``` 
scan_filter_chain:
- type: laser_filters/LaserArrayFilter
  name: laser_median_filter
  params:
    range_filter_chain:
      - name: median_5
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 5
          unused: 10
    intensity_filter_chain:
      - name: median_5
        type: filters/MultiChannelMedianFilterFloat
        params:
          number_of_observations: 5
          unused: 10

- name: interpolation
  type: laser_filters/InterpolationFilter

- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1

- name: dark_shadows
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 45000  #100
    upper_threshold: 50000  #10000
    disp_histogram: 0

- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: scan_link
    min_x: -1.0
    max_x: 1.0
    min_y: -1.0
    max_y: 1.0
    min_z: -1.0
    max_z: 1.0

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 2.0
    max_range_difference: 0.1
    filter_window: 2  
```

Here is my launch file:
```  
<launch>
<node pkg="laser_filters" type="scan_to_scan_filter_chain"
      name="laser_filter">
       <rosparam command="load" file="$(find test)/my_laser_config.yaml" />
       <remap from="scan" to="base_scan" />
     </node>
</launch>
 ```

I suspect there is something incorrect about my .launch file
