### ISSUE TITLE
angular_bounds_filter is not working on ROS2 Foxy

### ISSUE THREAD

**Issue by bxtbold** [ros-perception/laser_filters#167]
I have tried running [scan_to_scan_filter_chain](https://github.com/ros-perception/laser_filters/blob/ros2/src/scan_to_scan_filter_chain.cpp) node with the yaml file below, but filtered scan topic is the same as the original topic. I have tried changing the lower and upper angle ranges and it didn't seem to work at all.

```yaml
scan_to_scan_filter_chain:
  ros__parameters:
    filter:
      name: scan
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0
        upper_angle: 2.6
```

Thank you in advance

**Comment by bxtbold** [comment]
Solution:
it turned out parameter head name was `filter1` instead of `filter` (silly me)

```yaml
scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: scan
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0
        upper_angle: 2.6
```
