### ISSUE TITLE
LaserScanAngularBoundsFilter not working

### ISSUE THREAD

**Issue by hilmi-ica** [ros-perception/laser_filters#178]
Hey guys! I am trying to bound the angle of my lidar SICK NAV310 using laser_filters. Here's my launch file:
```
<launch>
<node pkg="laser_filters" type="scan_to_scan_filter_chain" output="screen" name="laser_filter">
      <!-- <remap from="scan" to="base_scan" /> -->
      <remap from="scan" to="/sick_nav_3xx/scan" />
      <rosparam command="load" file="$(find laser_filters)/examples/angle_filter_example.yaml" />
</node>
</launch>
```
and my yaml file:
```
scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  # type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.5708
    upper_angle: 1.5708
```
Using the `LaserScanAngularBoundsFilter` plugin it results in:
```
rostopic echo -n 1 /scan_filtered
header: 
  seq: 23
  stamp: 
    secs: 1680337311
    nsecs: 850266218
  frame_id: "cloud"
angle_min: -3.1415927410125732
angle_max: -3.1415927410125732
angle_increment: -0.004363323096185923
time_increment: 8.695651922607794e-05
scan_time: 0.125
range_min: 0.0
range_max: 100.0
ranges: [2.4720001220703125]
intensities: [0.0]
---
```
And using `LaserScanAngularBoundsFilterInPlace` results in:
```
rostopic echo -n 1 /scan_filtered
header: 
  seq: 88
  stamp: 
    secs: 1680337217
    nsecs: 659402847
  frame_id: "cloud"
angle_min: -3.1415927410125732
angle_max: 3.1415927410125732
angle_increment: -0.004363323096185923
time_increment: 8.695651922607794e-05
scan_time: 0.125
range_min: 0.0
range_max: 100.0
ranges: [2.4800000190734863, 2.4720001220703125, .....
```
Which didn't filter the LaserScan. I'm using ROS Noetice distribution.
Hope anyone can help! Thanks!

**Comment by adamkrawczyk** [comment]
the same for humble

**Comment by taarifmohamedrafi** [comment]
I had the same issue on ROS2 Humble where `laser_filters` installed system-wide (`apt install ros-humble-laser-filters`) did not apply the filters correctly.

What fixed it for me was doing a source install instead:

```
cd ~/ros2_ws/src
git clone https://github.com/ros-perception/laser_filters.git -b ros2
cd ..
colcon build
source install/setup.bash
```

After that, I used one of the example configs provided in the package.

YAML file:
```
scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.52
        upper_angle: 1.52
```
Launch file:
```
from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory


def generate_launch_description():
    return LaunchDescription([
        Node(
            package="laser_filters",
            executable="scan_to_scan_filter_chain",
            parameters=[
                PathJoinSubstitution([
                    get_package_share_directory("laser_filters"),
                    "examples", "angular_filter_example.yaml",
                ])
            ],
            remappings=[
                ('scan', '/lidar0/scan'),                 # INPUT
                ('scan_filtered', '/lidar0/scan_filtered')  # OUTPUT
            ]
        )
    ])
```
And the angle filter is now working. Hope this helps.
