### ISSUE TITLE
Creating multiple nodes when changing node name

### ISSUE THREAD

**Issue by rafal-gorecki** [ros-perception/laser_filters#214]
When I set name in launch file, I get the following error

```bash
[scan_to_scan_filter_chain-5] [WARN] [1743186960.346687424] [rcl.logging_rosout]: Publisher already registered for node name: 'laser_filter'. If this is due to multiple nodes with the same name then all logs for the logger named 'laser_filter' will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
```

```python
    laser_filter_node = Node(
        package="laser_filters",
        executable="scan_to_scan_filter_chain",
        name="laser_filter", # Removing this fix the problem
        parameters=[laser_filter_config],
    )
```

**Comment by rafal-gorecki** [comment]
This happened only for `laser_filter`. I'm not sure why is that.

**Comment by jonbinney** [comment]
Sounds like you're launching another node with the same node somewhere .....

**Comment by rafal-gorecki** [comment]
I understand that it may sound like that, but it looks more like an error related to the use of parameters (the name has nothing to do with it, and the error for another name did not appear because I did not change the node name in the parameters file)

Try to reproduce this problem on ROS jazzy with the file `~/params.yaml`

```yaml
---
/**/laser_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.1
        min_x: -0.17
        max_y: 0.12
        min_y: -0.12
        max_z: 0.2
        min_z: 0.0
        invert: false
```

and the command: 

```bash
ros2 run laser_filters scan_to_scan_filter_chain --ros-args --remap __node:=laser_filter --params-file ~/laser_filter.yaml
```
